### ISSUE TITLE
Add formula TYPE to `rit create formula` core command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#1016]
Related to this issue: https://github.com/ZupIT/ritchie-templates/issues/1

**What would you like to be added**:

- When executing the `rit create formula` command, we currently can choose:
   - 1 - The `formula command`, 
   - 2 - The `formula programming language`
   - 3 - The `formula workspace`

I would like to add another option, the `formula type`, that the user could select according to templates available for the chosen programming language.

_Note: This formula type should be selected in third position, after selecting the programming language, but before selecting the workspace._

**Why is this needed**:

- Now that there is a new template repository for formulas (https://github.com/ZupIT/ritchie-templates) it could be interesting to create templates which abstract various commons implementation.
- As today, the templates repository only support `hello-world` templates, the idea would be to add new templates such as `Empty`, `REST API consuming`, `Project Scaffolding` and so on... in as many programming language as possible.

**Comment by yanBrandao** [comment]
Hello Ritchie's folks

Hope you're all fine :)

According to this [[FEATURE] Add new formulas templates type](https://github.com/ZupIT/ritchie-templates/issues/1). The `formula type` option is already available?

We just need to create new templates?

**Comment by caroldf07** [comment]
HI @yanBrandao , if you take a look in: https://github.com/ZupIT/ritchie-cli/projects/7 < you'll gone see that issue is still pending. Is the first card from the column TO DO.

**Comment by caroldf07** [comment]
HI @yanBrandao , if you take a look in: https://github.com/ZupIT/ritchie-cli/projects/7 < you'll gone see that issue is still pending. Is the first card from the column TO DO.

**Comment by GuillaumeFalourd** [comment]
Hi @yanBrandao and @caroldf07 

If I'm not mistaken, this PR https://github.com/ZupIT/ritchie-cli/pull/1036 from @kelsoncarmozinezup already resolved this issue on the Ritchie V3 binary.

Can you confirm it @kelsoncarmozinezup ?

**Comment by kelsoncarmozinezup** [comment]
Hi @GuillaumeFalourd, @caroldf07, and @yanBrandao.

This issue was already solved on PR #1036. 

When executing the rit create formula command on v3, you will need to answer:

  1. The `formula command`;
  2. The `formula programming language`; 
         - The `formula type` - only If the language has more than one template;
  3. The `formula workspace`.

**Comment by GuillaumeFalourd** [comment]
Great! I'll close it then. Thanks 👍🏼
