### ISSUE TITLE
[BUG] Slash in new formula's command generate a path error

### ISSUE THREAD

**Issue by SalazarBruno** [ZupIT/ritchie-cli#108]
**What happened**: When trying to create a new formula, if you specify a command like `rit teste teste_sub/teste` in the "_new formula's command_" prompt, the resulting path is malformed and you receive a path not found error.

**What you expected to happen**: Either explicitly block backslash and forward slash in command or properly address them.

**How to reproduce it (as minimally and precisely as possible)**:
`rit create formula` > `rit teste teste/sub`
`rit create firmula` > `rit teste teste\sub`

**Anything else we need to know?**: Tested in windows only.

**Environment**:
- Ritchie version (use `rit --version`): 1.0.0-beta.6
- Operating System: windows 10
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by victor-schumacher** [comment]
Hi @SalazarBruno 
This bug is now on our backlog and gonna be solved asap.
We really appreciate your contribution, thanks.

**Comment by victor-schumacher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [validation of \ / on rit create formula](https://trello.com/c/1n6TMQ6N/412-validation-of-on-rit-create-formula)
