### ISSUE TITLE
[FEATURE] Resize website layout

### ISSUE THREAD

**Issue by LucasFelipeTimoteo** [ZupIT/ritchie-cli#140]
## Feature
 - The page is not well dimensioned horizontally. Resize the width

## Why
- It breaks the layout and UX

### Proof
![print](https://user-images.githubusercontent.com/49293338/83537149-8d592480-a4ca-11ea-8f98-b9f274fdeb08.png)

**Comment by viniciusramosdefaria** [comment]
This issue is gonna be closed because we're planning a new landing page.
