### ISSUE TITLE
[BUG]Error on login when password contains special character

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#168]
**What happened**:

Error when password contains special characters on windows

**What you expected to happen**:

Password accepts all characters

**How to reproduce it (as minimally and precisely as possible)**:

Login with any user with password with character ! (exclamation)

**Anything else we need to know?**:

Error reported by windows user on cygwin, prompt and powershell

**Environment**:
- Ritchie version (use `rit --version`): 1.0.0-beta-14(team)
- Operating System: Windows
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Evidences**:

![image](https://user-images.githubusercontent.com/58859234/84833517-d39f9f00-b005-11ea-9748-9ac90a434d7a.png)

**Comment by kaduartur** [comment]
@fabianofernandeszup, this error was fixed in **1.0.0-legacy (team)** version.

thanks for contributing with Ritchie-CLI!
