### ISSUE TITLE
[BUG] Error when adding kubeconfig too big

### ISSUE THREAD

**Issue by erneliojuniorzup** [ZupIT/ritchie-cli#173]
**What happened**:

**What you expected to happen**:

`Kubeconfig credential saved!`

**How to reproduce it (as minimally and precisely as possible)**:

`rit set credential`
`Provider: kubeconfig`
`credential: base64config="kubeconfig in base64 a long time"` 

**Environment**:

- Ritchie version (use `rit --version`):

`rit version 1.0.0-beta.14 (single)
  Build date: 06/15/20_14:00
  Built with: go1.14.4
`

- Operating System:

`NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by victor-schumacher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Set credential too long text](https://trello.com/c/lgQvueCX/481-fix-set-credential-too-long-text)

**Comment by viniciusramosdefaria** [comment]
Closing issue, code already in review.
