### ISSUE TITLE
[FEATURE] rit build formula command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#176]
**What would you like to be added**:

- O command to build a formula instead of having to enter inside the repository to execute the `make test-local `command.

**Why is this needed**:

- To make the test of a new implementation easier.

**Comment by kaduartur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE UX] rit build formula](https://trello.com/c/wepGioHa/433-feature-ux-rit-build-formula)
