### ISSUE TITLE
[FEATURE] Enhancement of the rit set credential command on single version

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#177]
**What would you like to be added**:

- Turn the `rit set credential` command easier on the Single version. Listing available providers the same it's done on the Team version 

> ➜  rit set credential
> ✔ ME (for you)
> Use the arrow keys to navigate: ↓ ↑ → ←
> Provider:
>  ▸ darwin
>      email-org
>      github
>      gitlab
>      jenkins
>      kubeconfig
>      aws

This list of provider configurations could be updating according to community needs by opening a PR on the ritchie-cli repository.

**Why is this needed**:

- It's a bit complicated to manipulate credentials on the Single version as it is now.

**Comment by victor-schumacher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE UX] Retornar uma lista de providers também para a versão Single do RIT SET CREDENTIAL](https://trello.com/c/Flgorivj/451-feature-ux-retornar-uma-lista-de-providers-tamb%C3%A9m-para-a-vers%C3%A3o-single-do-rit-set-credential)
