### ISSUE TITLE
[FEATURE] rit list credential command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#178]
**What would you like to be added**:

- To know which credentials have been added on the current context (it won't be necessary to see the values, but at least the field_name to know how to manipulate those variables inside a formula).

**Why is this needed**:

- There is no way to know what credentials are defined on the context today.

**Comment by victor-schumacher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Feature] list credential](https://trello.com/c/jAnJO0JY/499-feature-list-credential)
