### ISSUE TITLE
[FEATURE] Adding hello world template in C# (rit create formula)

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#179]
**What would you like to be added**:

- A _Hello World_ template to create a formula in C# with the rit create formula command

**Why is this needed**:

- Those templates are currently available for Java, Go, Python, Node and Shell. It would make it easier for C# programmers to create formulas and use Ritchie.

**Comment by victor-schumacher** [comment]
Moving this issue to ZupIT/ritchie-formulas#111
