### ISSUE TITLE
[FEATURE] Adding hello world template in RUST (rit create formula)

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#181]
## What would you like to be added:

A Hello World template to create a formula in Rust with the rit create formula command

## Why is this needed:

Those templates are currently available for Java, Go, Python, Node and Shell. It would make it easier for Rust programmers to create formulas and use Ritchie.

**Comment by victor-schumacher** [comment]
Moving this issue to ZupIT/ritchie-formulas#111
