### ISSUE TITLE
[BUG] make test-local doesn't work with space in PATH obtained with PWD command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#183]
**What happened**:

- The following line in the make test-local script returned an error :
`for formula in $(FORMULAS); do cd $$formula/src && make build && cd $(PWD_INITIAL); done
`

**What you expected to happen**:

- Execute the make test-local command without any error.

**How to reproduce it (as minimally and precisely as possible)**:

- Execute the command make test-local with a space in the PATH when executing the PWD command :
Example : `/Users/Name Firstname/ritchie-formulas-local`

**Anything else we need to know?**:

- A solution could be to add " around the PWD value inside the test-local script.

- This correction needs to be implemented on the template for creating new formulas as well as in each formula repository.

**Environment**:
- Ritchie version (use `rit --version`): rit version 1.0.0-beta.14 (team)
- Operating System: WINDOWS
- Network plugin / Tool and version (if this is a network-related / tool bug): N/A
- Others: N/A

**Comment by viniciusramosdefaria** [comment]
This makefile does not exist anymore. Closing issue.
