### ISSUE TITLE
[BUG] Creating python formulas with dependencies

### ISSUE THREAD

**Issue by faermanj** [ZupIT/ritchie-cli#223]
Tried to use rit to create a simple CLI to read my google calendar using this code:
https://developers.google.com/calendar/quickstart/python

Works on standalone but on rit errors:
ModuleNotFoundError: No module named 'googleapiclient'

Not sure how if this is a documentation issue about building python formulas or something else.

Halp?

**Comment by GuillaumeFalourd** [comment]
Hi @faermanj 

Thank you for opening this issue. 

We are checking this problem and keep you informed once we'll identify the reason it's happening.

**Comment by victor-schumacher** [comment]
By now, you can try
`$ pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib` 
on ~/ritchie-formulas-local

**Comment by faermanj** [comment]
Cool, thanks a lot! I moved the project to Java, but i think the examples with dependencies is quite commonly needed.

**Comment by viniciusramosdefaria** [comment]
The team is working on a new way to manage deps.

**Comment by viniciussousazup** [comment]
move to formula repository https://github.com/ZupIT/ritchie-formulas/issues/131
