### ISSUE TITLE
[BUG] - Add the version of the repository to the docker image generated

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#380]
**What would you like to be added**:
Add the version of the repository to the docker image generated when the formula is run with docker. Ex: REPO_FORMULA_1.0.0

**Why is this needed**:
So that formulas always have a current docker image consistent with their version. Otherwise, the formula will never
it would have an update of the docker image, it would always be executed on the first image created.

**Comment by viniciussousazup** [comment]
i thing that this docker image is used only for cache add version of formula is not necessary, since every time that you run with docker flag we build the docker file again
