### ISSUE TITLE
[FEATURE] - Add core command to set the default type of formula execution

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#381]
**What would you like to be added**:
Add core command to set the standard type of formula execution, either with docker or locally. Also add the --local and --docker flags so that it is possible to force a certain type of execution even if the default type is different.

**Why is this needed**:
So that the formula user does not always have to type --docker if he always wants to run his formulas with a docker.

**Comment by viniciussousazup** [comment]
I thing core command do not need the --docker flag since this flag is used to run a formula that your computer not supported, all the formulas on core are already compiled so this formulas can be run on all computers

**Comment by brunasilvazup** [comment]
Hi,
This issue will be treated in https://github.com/ZupIT/ritchie-cli/issues/443.
