### ISSUE TITLE
Use github credentials to add private repo.

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#382]
**What would you like to be added**:
Use github credentials to add private repo.

**Why is this needed**:
 So that it is not necessary to manually consult a credential or generate a new one.

**Comment by brunasilvazup** [comment]
Hello,
This situation had already been considered and the credentials part focuses on formulas.

In addition, another important aspect is that the added repository may not refer to the github saved in the credential, causing problems with automatic authentication.
