### ISSUE TITLE
[BUG] - Formulas with the same directory structure are causing an error in the build and execution

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#383]
**What happened**:
Formulas with the same home directory structure are causing an error in the build and execution.

**What you expected to happen**:
That each formulas be executed independently, as in v1.

**How to reproduce it (as minimally and precisely as possible)**:
Create a formula like ```$ rit a b``` and another one like ```$ rit a b c```.
As soon as you build the formula ```$ rit a b c``` rit will build a ```$ rit a b```

**Anything else we need to know?**:

**Environment**: All
- Ritchie version (use `rit --version`): 2.0.2
- Operating System: All
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by victor-schumacher** [comment]
@fabianofernandeszup this bug is truly happening.
Ideas of solutions or pull requests are welcome about this.
