### ISSUE TITLE
[FEATURE] - Check config.json before executing the formula and inform if the user needs to pass credentials.

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#384]
**What would you like to be added**:
 Check config.json before executing the formula and inform if the user needs to pass credentials.

**Why is this needed**:
To improve the user experience, since in some formulas all fields are filled and only at the end the error is generated stating that a credential should be set.

**Comment by viniciusCSreis** [comment]
Today this message are showed, when you run a formula that use a CREDENTIAL on config.json and you not set this credentials:

```
Error:
Fail to resolve credential for provider aws.
Try again after use:
        ∙ rit set credential
```

**Comment by brunasilvazup** [comment]
Hi,
This problem will be resolved in https://github.com/ZupIT/ritchie-cli/issues/385.
