### ISSUE TITLE
[FEATURE] - Allow formulas without dockerfile and only run locally

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#386]
**What would you like to be added**:
If a given formula does not have a dockerfile, inform that it only allows local execution, and ask if you want to continue, instead of giving an error message.

**Why is this needed**:
Not to generate error in formulas that have only local execution.

**Comment by kaduartur** [comment]
Hi @fabianofernandeszup, this issue will be solved in the next release.

thanks!
