### ISSUE TITLE
Conditional options on config.json

### ISSUE THREAD

**Issue by rasouza** [ZupIT/ritchie-cli#390]
**What would you like to be added**:
I'd like to show an option based on the answer of the previous option
**Why is this needed**:
So I can deliver a better experience to the user by removing unnecessary questions depending on his/her answer

**Comment by victor-schumacher** [comment]
@rasouza that sound's nice! Thanks for the idea.
Today cli reads inputs from config.json on this file:
https://github.com/ZupIT/ritchie-cli/blob/4d0af9c251e9b28139694df0458caa53d65da8f3/pkg/formula/runner/inputs.go#L115

The implementation of conditional options will probably go there.
Pull requests about this feature are welcome.

**Comment by henriquemoraeszup** [comment]
Hey @rasouza ! thanks for your suggestion. Your request is currently under review on #454.
Stay calm, and automate everything 👊
