### ISSUE TITLE
Command line validation

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#393]
**What would you like to be added**:

- Returning a message if the executed command line doesn't exists.

**Why is this needed**:

- Currently, if you digit ```rit init dennis ritchie``` the command ```rit init``` is executed, there is no validation of the full command executed.

- Someone executing a command for the first time without looking at the documentation might not understand which command has been executed.

![rit init dennis ritchie](https://user-images.githubusercontent.com/22433243/89796708-56be0c80-db00-11ea-8fce-53cef7865a50.png)

**Comment by brunasilvazup** [comment]
Hi @GuillaumeFalourd
When analysing this issue, we identified that is a bug.
We be fix this, thanks for contribution.
