### ISSUE TITLE
Not adding community repo leads to unpredictable behavior

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/ritchie-cli#402]
**What happened**:
After initializing and adding a new repo without the community, the cli keeps asking to run `rit init`, commands like `rit list repo` or even formulas do not work as Ritchie only asks for the init command

**What you expected to happen**:
After initializing and adding a repo without the community one, it should list in the command and not keep asking to run `rit init`

**How to reproduce it (as minimally and precisely as possible)**:
* Download Ritchie
* Run rit init and **do not ** accept the community repo
* Add a repo
* Run other command such as a formula or `rit list repo`

**Environment**:
- Ritchie version 2.0.3:
- Operating System: Ubuntu 18.04

**Comment by brunasilvazup** [comment]
Hello @henrique, thanks for your contribution.

I tested following the steps indicating and on the same version of ritchie/OS and the ritchie worked normally.

Follow the steps I used:
```bash
# Clean environment
rm -rf ~/.rit && rm -rf ~/ritchie-formulas-local
sudo rm /usr/local/bin/rit

# Install
curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash

# Init without commons
rit init

# Adds personal formula repository*
rit add repo

# Test
rit list repo
rit create formula
```

*: use 'commons' as the repository name and the informed repository must have the templates folder (https://github.com/ZupIT/ritchie-formulas/blob/master/templates).

Please test again following the steps indicated and if the error persists please reply to this issue.

**Comment by henriquemoraeszup** [comment]
Hi @brunasilvazup , I understand the correct way of making a repo work, but don't you think this solution is overly opinionated? I as a user had no idea I would have to provide a specific name and add a specific folder to my formulas project to make Ritchie working properly

**Comment by kaduartur** [comment]
We will just block the `rit create formula` command, so the user can execute formulas and other core commands. Just to create formulas you must add a repository with the name "commons".

In the future, we will look again at a better solution to this problem.

Thanks for contributing!
