### ISSUE TITLE
[FEATURE] Functional tests for upgrade

### ISSUE THREAD

**Issue by lucasdittrichzup** [ZupIT/ritchie-cli#419]
**What would you like to be added**:
- Tests for the core `upgrade` command

**Why is this needed**:
- Ensure that the command is working as expected
- Increase the code coverage of the project

**Comment by viniciussousazup** [comment]
What type of test you are suggesting ? To the upgrade flow we already have this test:

https://github.com/ZupIT/ritchie-cli/blob/master/pkg/cmd/upgrade_test.go
https://github.com/ZupIT/ritchie-cli/blob/master/pkg/upgrade/manager_test.go
https://github.com/ZupIT/ritchie-cli/blob/master/pkg/upgrade/url_finder_test.go
https://github.com/ZupIT/ritchie-cli/blob/master/pkg/version/version_test.go
