### ISSUE TITLE
[FEATURE] Downloading programming languages dependencies on demands

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#427]
**What would you like to be added**:

- When executing a formula locally in a specific programming language, if I don't have the programming language version necessary to execute it, let Ritchie download it for me.

**Why is this needed**:

- Today, if I don't have the programming language installed on my computer, I have to stop using Ritchie, look for a way to install it, before coming back to Ritchie CLI.

**Comment by kaduartur** [comment]
Hello @GuillaumeFalourd, we see that Ritchie-CLI must not configure the user's computer to run the formulas. In the next version, the user will be warned that he must have the languages ​​already installed to run formulas locally or use the docker for that.

Thanks for collaborating!

**Comment by GuillaumeFalourd** [comment]
@kaduartur 

Wouldn't it be interesting to ask the user if he wants Ritchie CLI to install the language for him instead ?

I updated the ISSUE, and if that would be ok for you, I'll reopen it.
