### ISSUE TITLE
Download Ritchie OS requirements when installing.

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#428]
**What would you like to be added**:

- Each OS has a few configurations required to use Ritchie [Linux](https://docs.ritchiecli.io/getting-started/installation/linux), [MacOS](https://docs.ritchiecli.io/getting-started/installation/macos), [Windows](https://docs.ritchiecli.io/getting-started/installation/windows). 

*It would be great to realize those configuration for each OS during the tool installation*

**Why is this needed**:

- To avoid the user to spend time searching and downloading some extra tools required to be able to use Ritchie efficiently.

**Comment by victor-schumacher** [comment]
It would be nice if we list all the requirements by OS on this issue.

**Comment by GuillaumeFalourd** [comment]
The link to the documentation with requirements for each OS is in the ISSUE @victor-schumacher

**Comment by victor-schumacher** [comment]
@GuillaumeFalourd Hi! 
We are working on removing make dep on # 436. So I don't think it will be necessary to download the installation requirements.
Thank you.
