### ISSUE TITLE
Detect new formula repositories releases

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#431]
**What would you like to be added**:

- I would like the Ritchie CLI to detect when a new release of my imported repositories has been generated. And ask me if I want to import it automatically.

**Why is this needed**:

- Today, the user has to check if one of the imported formula repository (with the **rit add repo** command) has a new release to update it (one by one with the **rit update repo** command).

**Comment by brunasilvazup** [comment]
Phases:
- [ ] Tests created for the rit update repo command
- [ ] Inform the user when any local formula repository has a new release available (In the rit core command or the list repo)
