### ISSUE TITLE
[FEATURE] Don't execute locally if docker not installed when using flag

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#437]
**What would you like to be added**:

- Inform the user with an explicit message if --docker flag is used and Docker is not installed or started.

**Why is this needed**:

- When executing a command using --docker flag, if docker is not installed, Ritchie currently try to execute the command locally. (Returning an error message if the make command isn't installed.)

**Comment by kaduartur** [comment]
Hello @GuillaumeFalourd, this issue will be solved in the next release!

**Comment by kaduartur** [comment]
Hello @GuillaumeFalourd, this issue will be solved in the next release!
