### ISSUE TITLE
When build fail locally, suggest user to use --docker flag

### ISSUE THREAD

**Issue by rodrigomedeirosf** [ZupIT/ritchie-cli#439]
**What would you like to be added**:
Sometimes the user doesn't have the environment configured to run a formula locally, so when Ritchie to fail to build a formula, could suggest user to run inside a container

**Why is this needed**:
Show a message to user try to use the flag --docker

**Comment by brunasilvazup** [comment]
As we have another issue that will update the local and docker execution flow we will wait for it to finish to reassess the need.
> https://github.com/ZupIT/ritchie-cli/issues/443
