### ISSUE TITLE
Add a language check before executing a formula

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#444]
**What would you like to be added**:

- I would like Ritchie to inform me if I want to execute a formula in Go and I don't have Golang installed on my computer (idem for other programming language) before building the formula for the first time.

**Why is this needed**:

- Actually, I receive an unfriendly error when executing a formula coded in a programming language I'm not using. Which is not a great experience.

**Comment by henriquemoraeszup** [comment]
Closing this issue as it should be resolved in the formulas repo
