### ISSUE TITLE
Create new command rit list context

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#474]
**What would you like to add**:
Command to list existing contexts.

**Why this is necessary**:
To make managing contexts easier and following the list command pattern.

**Comment by kaduartur** [comment]
we didn't create the rit list context command because when you use the rit set context or rit delete context commands they are already listed. 

why do you think it would be necessary?

**Comment by lucasdittrichzup** [comment]
![](https://media.giphy.com/media/EYt3cjQTo7QHOsNyxb/giphy.gif)

**Comment by henriquemoraeszup** [comment]
Closing for lack of response and since `rit set credential` already lists the credentials
