### ISSUE TITLE
[Feature] - rit clean temp

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#476]
**What would you like to add**:
Command to clean the tmp folder of formulas that were not automatically removed.

**Why this is necessary**:
So that the user does not have to find the directory and delete this folder alone when it will start to be of considerable size.

**Comment by kaduartur** [comment]
Hello @fabianofernandeszup, we should not create a command for this, we will analyze why the tmp folder is not being removed when the execution of a formula fails.

We opened a new issue for this #502 

Thanks for your collaboration!
