### ISSUE TITLE
Wrong error message when the organization is not right

### ISSUE THREAD

**Issue by leandrorodrigueszup** [ZupIT/ritchie-cli#491]
**What would you like to be added**:
I've had a bad experience trying to configure ritchie in the legacy version (1.0.0-legacy (team)).
After typing `rit init`, I was asked for the organization name. I put name capitalized. (Myorg)
Then, I put the server URL.

But when I've tried to login (eg. `rit login`), I've got: Error: server (https://my.server.url) returned 404 Not Found

The issue was the organization name: In my case, it shouldn't be capitalized

**Why is this needed**:
I would be better if I've got the root cause of the error. In that case, the organization name was wrong.

Thanks!

**Comment by henriquemoraeszup** [comment]
Closing due to being related to the legacy version, which is no longer supported
