### ISSUE TITLE
Add a link to documentation on HELPER

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#501]
**What would you like to be added**:

- Add a link to Ritchie Documentation: https://docs.ritchiecli.io/ on the rit --helper command.

**Why is this needed**:

- If the user wants to deeper his knowledge.

**Comment by ritwikchakraborty123** [comment]
Hai I want to contribute in this issue

**Comment by GuillaumeFalourd** [comment]
Sure @ritwikchakraborty123 👍
I've assigned it to you.
Thank you for contributing!
