### ISSUE TITLE
Improves code quality related to linters and tests

### ISSUE THREAD

**Issue by brunasilvazup** [ZupIT/ritchie-cli#510]
**What would you like to be added**:

Improved code quality. For this, in discussion, we chose:

- [ ] Review functional tests
- [ ] Add more linters or review current ones
- [ ] Reformulate unit test 
- [x] Apply goimport > https://github.com/ZupIT/ritchie-cli/pull/509

**Why is this needed**:

To improve the quality and reliability of the code.

**Comment by lcd1232** [comment]
I'll do this

**Comment by GuillaumeFalourd** [comment]
Hi @lcd1232 , thank you for your message 👍🏼 
I'll assign you the ISSUE.
