### ISSUE TITLE
Add the formula templates to ritchie-cli

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#511]
**What would you like to be added**:
I would like to add formula templates to Ritchie-cli

**Why is this needed**:
Because the user needs to add a commons repo to start to create formulas on Ritchie-cli.

**Comment by kaduartur** [comment]
To make the collaboration easy, we will move the [templates](https://github.com/ZupIT/ritchie-formulas/tree/master/templates) folder to the ritchie-cli.

**Comment by fabianofernandeszup** [comment]
This aproach is not compatible with LTS.
