### ISSUE TITLE
Add all available flags in the ritchie options listing.

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#522]
**What would you like to be added**:

Add all available flags in the ritchie options listing.
Ex: --verbose --local --docker --stdin

Today only the --version tag is being displayed.

![image](https://user-images.githubusercontent.com/58859234/93159685-25c78d80-f6e5-11ea-9b56-07f1a42e1a18.png)

**Why is this needed**:

So that the user knows about the existence of these options, without having to consult the documentation for this.

**Comment by kaduartur** [comment]
Hello @fabianofernandeszup, the cobra framework works like this. It shows the flags by command.
For example:
The `rit` command only has the `--version` flag
The `rit demo hello-world` command has three flags
- `--docker`
- `--local`
- `--verbose`
To see this, execute `rit demo hello-world --help` command.

![image](https://user-images.githubusercontent.com/17505818/93229063-8e962080-f74c-11ea-80c5-8c9d7f861f28.png)

**Comment by fabianofernandeszup** [comment]
Cool, so I'm going to close this Issue. Thank you.
