### ISSUE TITLE
Improve 'rit completion bash' command output

### ISSUE THREAD

**Issue by victor-schumacher** [ZupIT/ritchie-cli#524]
**What would you like to be added**:

A useful output, informing the command result.
Todays output:
![image](https://user-images.githubusercontent.com/31257422/93262339-75a46400-f77a-11ea-88b0-aae3d3ebe6e1.png)

**Why is this needed**:
To understand whether the command was successful or not

**Comment by ng29** [comment]
Hey @victor-schumacher 

More info on this will be appreciated, so that can work on this 👍

**Comment by ng29** [comment]
> > Hey @victor-schumacher
> > More info on this will be appreciated, so that can work on this
> 
> Hi @ng29
> Today the command `rit completion bash` logs alot of useless things, the result is not clear.
> The purpose of this issue is to improve the command output, making it compressible.
> It became clearer?

Ahh @victorschumacherzup got clarity on some things in my mind, but can you please share the directory where this command is located. ??

**Comment by victorschumacherzup** [comment]
Of course @ng29 .

https://github.com/ZupIT/ritchie-cli/blob/e29c5315bb7d4eab48a1e764b54a9f5492329c99/pkg/cmd/autocomplete.go#L83
