### ISSUE TITLE
'rit tutorial' command shows the same output for enabled or disabled

### ISSUE THREAD

**Issue by victor-schumacher** [ZupIT/ritchie-cli#525]
**What would you like to be added**:

Different text or color according to my choice

**Why is this needed**:
It is confusing.

**Comment by ravindrabhargava** [comment]
Hi Let me understand it a bit more to work on it

**Comment by victor-schumacher** [comment]
Hi!
Using the command ```rit tutorial``` , it shows two options, which are disable and enable, and both of them shows the same output when select. The ouput is ``` Set tutorial successful! ``` 

The idea of this issue is to output different things according to the choose.
Like "Tutorial enable" and "Tutorial disable"

![tuto](https://user-images.githubusercontent.com/31257422/93488555-e06db080-f8dc-11ea-810b-e83f16926810.png)

**Comment by ravindrabhargava** [comment]
thanks for the clarification, I will work on it, please assign this to me.
