### ISSUE TITLE
Allow more languages for the TUTORIAL tips.

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#528]
**What would you like to be added**:

- A new command to configure the language in which the TUTORIAL will be displayed on Ritchie.

Suggestion: ```rit set tutorial-language```

**Why is this needed**:

- Today, the tutorial is only available in ENGLISH, but not everyone speaks this language (not even 5% of Zup company's country: Brazil).

- If there are ;any languages available, the product will be used by more people.

**Comment by ritwikchakraborty123** [comment]
Hai I want to contribute

**Comment by GuillaumeFalourd** [comment]
Sure @ritwikchakraborty123 👍 
I've assigned it to you.
Thank you for contributing!

**Comment by ritwikchakraborty123** [comment]
Sir can you guide me to run it locally... means what are the requirements to run the codebase... thanks sir

**Comment by GuillaumeFalourd** [comment]
Hi @ritwikchakraborty123 , 

You'll need to have *golang* installed as well as the *make* command.

Then use the make command at the root of the project to execute the build script on the *Makefile*: https://github.com/ZupIT/ritchie-cli/blob/master/Makefile

For example with linux: `make build-linux`

This command will create an executable file on a `dist` folder (root) according to the OS informed.

You'll then be able to execute the binary you've created going into the OS folder (with linux it will be `/dist/linux`) to check your implementation using `./rit` as it would be the `rit` command (ex: `./rit init` or `./rit demo hello-world`)

**Comment by lordvins226** [comment]
Hi. I want to contribute for french.

**Comment by GuillaumeFalourd** [comment]
Great @lordvins226 , thank you for contributing 👍 
Let us know if you need something.

**Comment by mateusmb** [comment]
Hello, everyone, hope that everybody is well!

How is the progress for this issue? I would like to contribute, specially for portuguese translation. 
I am walking through the source code and taking notes where the tutorial messages are set. I am considering using go-i18n for localization and translation. Is there some work done alreay?

Thank you.

**Comment by GuillaumeFalourd** [comment]
Hi @mateusmb , thank you for your message 👍🏼 
We didn't receive any contribution regarding that ISSUE yet.
I believe the first things to do would be to create the `rit set tutorial-language` command, and then evaluate the best way to store messages for each language.
Do you want to be assigned to the ISSUE as well ?

**Comment by mateusmb** [comment]
Yes, @GuillaumeFalourd, I do want to be assigned, thank you!

So, in order to successfully implement a set command for tutorial-language, I need to create a function which receives at least an inputList and returns a cobra.Command, correct? If so, I will follow the code of others set commands, for example, NewSetPriorityCmd.

From there I will reconsider how I can achieve the internationalization for the tutorial messages.

**Comment by GuillaumeFalourd** [comment]
You can follow with something like this for the new command, yes.

Now, I'm wondering how the system will get the list of available languages without having it implemented manually inside the function.
I could interesting to have a folder with all messages associated to each language.
That way, the system could check this folder to know how many languages are available to return the list to the user.
I believe that would be great, and would make it easier to add other languages in the future.
Something like this:
```
/languages/
      |_ en
          |_ messages.txt
      |_ br
          |_ messages.txt
```

or 

```
/languages/
      |_ en-messages.txt
      |_ br-messages.txt
```

What do you think ?

**Comment by mateusmb** [comment]
Yes, I was wondering something like this. 

I am doing with the first directory tree approach, as I need only to get the folders under the languages directory.

But would be better if the folders names could be mapped to the full languages names, so, instead of having something like:

```
? All: [use arrows to move, type to filter]
> en
> pt
> ja
```

We could have something like:

```
? All: [use arrows to move, type to filter]
> English
> Português
> 日本語
```

For this approach, I would need to add a file (like a json) with the folders names as keys and full names as values, for example. And everytime a language is added, this file should be updated also.

**Comment by GuillaumeFalourd** [comment]
Looks good to me 👍🏼

**Comment by GuillaumeFalourd** [comment]
This ISSUE will now be treated by the Core Team, through this new ISSUE: https://github.com/ZupIT/ritchie-cli/issues/775 
And other that will be related later.
