### ISSUE TITLE
hello-world demo fails using --docker

### ISSUE THREAD

**Issue by icheko** [ZupIT/ritchie-cli#531]
**What happened**: I'm trying to run the demo  and errors with `unable to create context store: $HOME is not defined
Error: exit status 1` is returned.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. `rit demo hello-world --docker`

**Anything else we need to know?**: Running it as local works `rit demo hello-world --local`. It seems other commands are failing with the same error code when using --docker.

**Environment**:
- Ritchie version (use `rit --version`):

rit version 2.0.5
  Build date: 09/08/20_20:43
  Built with: go1.14.8

- Operating System: macOS Mojave 10.14.6 (18G4032)
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

<details>
  <summary>go env</summary>
```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/jose.s.pacheco/Library/Caches/go-build"
GOENV="/Users/jose.s.pacheco/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jose.s.pacheco/source/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hy/bmtcj7kd1fv0qkxhp72mhg880000gp/T/go-build040953335=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

**Comment by GuillaumeFalourd** [comment]
Hi @icheko , thank you for reporting this bug 👍 
We will check this problem and try to resolve it as soon as possible.

**Comment by GuillaumeFalourd** [comment]
After a few research @icheko , the problem might be deeper and directly related to Docker, as inform on this ISSUE: https://github.com/docker/for-mac/issues/4919

**Comment by icheko** [comment]
@GuillaumeFalourd appreciate the quick turnaround 🏆 . Killed a few hours trying to get this to work on my local.

**Comment by cristiancmello** [comment]
@GuillaumeFalourd **WSL2 with Docker for Windows Home** have same bug
