### ISSUE TITLE
When creating a new formula, create a specific repository for this workspace

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#550]
**What would you like to be added**:
I would like to split local repos by workspace names.
For example:
`formula-workspaces.json`
```json
{
   "My-workspace-1":"/home/user/workspace-1",
   "My-workspace-2":"/home/user/workspace-2"
}
```

The local repositories names:
- `~/.rit/repos/My-workspace-1`
- `~/.rit/repos/My-workspace-2`

Today when I create a new formula named `rit test formulas` to `My-workspace-1` the build sent my new formula to **~/.rit/repos/local** and if I create a new formula with the same name to `My-workspace-2` the formula created in `My-workspace-1` to be overite in the local repo.

A good approach is to create a repo with the same workspace name, so that we can use the repo feature for local repositories like `rit delete repo`,` rit set repo-priority` among others. so we will no longer have conflicts with local formulas

**Why is this needed**:
When I create a formula that has the same name as another formula created locally, it overrides because this formula always is sent to the local repo.

**Comment by henriquemoraeszup** [comment]
It is important to prefix the name to not conflict with a repo name
