### ISSUE TITLE
Unify and Simplify Context and Credential files and suggest the use of the file to set batch context and credentials 

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#556]
**What would you like to be added**:

I would like the context and credential command files to be simplified (and maybe unified), and to be add a tip when using the command to indicate the use of the file to manage batch of contexts and credentials.

**Why is this needed**:

While working in teams or with lots of credentials, setting up the contexts and credentials one by one is time consuming, so it would be good if we could simplify the process and suggest the use of the file to set them in batch. But in order for this to be a option, the context file and the credential files should be unified, to make it easy.

AWS CLI example:

In the credential file you have the information between [] as the profile (similar to context) and you just set the credentials below. Making it simple to organize it.

[default]
aws_access_key_id=
aws_secret_access_key=

[xx-team]
aws_access_key_id=
aws_secret_access_key=

[xx-prod]
aws_access_key_id=
aws_secret_access_key=

**Comment by henriquemoraeszup** [comment]
Closing due to idleness or lack of more requests for this feature
