### ISSUE TITLE
Add Research feature on the CLI

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#557]
**What would you like to be added**:

I would like to add a feature to allow the product and design team to research users inside the CLI, in order to understand the user's perception. It would be nice if we could use a third party provider to create the researchs and set the triggers for when they will appear, and also to see the answers easily.

**Why is this needed**:

For us to understand more about the CLI's users.

**Comment by GuillaumeFalourd** [comment]
After discussing with the Team, we identify a formula could be created to perform this operation. This doesn't have to be a core command.
