### ISSUE TITLE
Suggest a build when the formula is used and we notice that a modification was made in the files

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#559]
**What would you like to be added**:

When the formula is used and the files are different from the last use, suggest a build option automatically.

Or build automatically (without asking) when a modification is noticed

Ex:

rit clubhouse create story

- We've noticed your files have modifications from last build, do you want to build the formula? 
yes
no

If the answer is yes

Build automatically

**Why is this needed**:

Improve usability. If you are making modifications, is likely you want to use the latest version.

**Comment by gabriel-pinheiro** [comment]
Hey, I'd like to take this issue, can I get it assigned to me?

**Comment by henriquemoraeszup** [comment]
It's all yours @gabriel-pinheiro =]
