### ISSUE TITLE
Increase test coverage rate

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#560]
**What would you like to be added**:

- I would like the *Codecov* rate coverage to be higher (currently 78% cf README).

**Why is this needed**:

- The higher the test coverage rate, the higher will be the product quality.

**Comment by adi-mohan** [comment]
For this to be done, you need to have a .codecov.yml in .github/ path configured.

**Comment by GuillaumeFalourd** [comment]
Hi @adi-mohan , thank you for your message.

I don't think it's necessary in that case as we run the Codecov analysis in our Circleci pipeline and get the datas afterwards from https://codecov.io to display them on the repository README file.

Is your suggestion a good practice for Codecov use ?

**Comment by adi-mohan** [comment]
No. I am new to these technologies. I was curious and was digging in and I found some repositories which have this yml configured at that path. Otherwise, I think someone with the admin rights may only change the coverage rate as desired.

**Comment by GuillaumeFalourd** [comment]
Good to know, thanks @adi-mohan 👍🏼 
We actually plan to remove codecov or update the way we use it so we mat go for another tool in the next weeks.

**Comment by henriquemoraeszup** [comment]
Closing as the current cov rate is above 85% and since @brunasilvazup is responsible for further increasing their reliability
