### ISSUE TITLE
To improve the user experience implement shortcuts like bash

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#571]
**What would you like to be added**:

Would like commands to support shortcuts like bash (ctrl + R and others).
Follow the list: 
https://www.vivaolinux.com.br/dica/Coletanea-de-atalhos-no-bash

**Why is this needed**:

To improve usability

**Comment by panos** [comment]
Hey, it's sort of hard for me to comprehend the contents of that blog post. Also, do you need someone to **add shortcuts like the ones you can find in Bash** or **add a shortcut for Bash itself**? (I'm presuming you meant the former)

**Comment by leticiasilvazup** [comment]
Hey Panos! I'm sorry for the mistake about the link and about the issue itself. Thinking further, I understood that the idea is invalid for now.
