### ISSUE TITLE
Fix broken link CONTRIBUTING.md

### ISSUE THREAD

**Issue by Harirai** [ZupIT/ritchie-cli#576]
The community guidelines link is broken in repositories.  
Currently pointing to [Ritchie community guidelines](https://docs.ritchiecli.io/community), link to the [FAQs](https://docs.ritchiecli.io/faq) seems to be a good option.

I'd like to make the above changes if they seem correct. 
(Other repositories also have the same issue, should I send PR for each of them?)

**Comment by GuillaumeFalourd** [comment]
Great issue @Harirai , thank you 👍 
Would you like to do it to contribute for the Hacktoberfest event ?
