### ISSUE TITLE
Allow for inputs to be added via flag params

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/ritchie-cli#579]
**What would you like to be added**:
Allow input parameters to be added as flags
i.e: `rit github create project --project-name="my new project"`

**NOTE:** There will need to be introduced the concept of reserved flags or variable names

**Why is this needed**:
From multiple meetings, we have noticed developers request this feature to increase productivity and user experience

**Comment by GuillaumeFalourd** [comment]
@henriquemoraes8 
Won't this feature turn the STDIN flag use obsolete ?

**Comment by henriquemoraeszup** [comment]
Not unless we deprecate it, it makes it easier this way for users to pass parameters, but with stdin might make it simpler for other automated programs to build the call. Both have their own benefits 😄

**Comment by GuillaumeFalourd** [comment]
Ok. Let's test it and check which one get the better adoption. 
Then, we'll eventually deprecate the other one with time.

**Comment by henriquemoraeszup** [comment]
@GuillaumeFalourd My point is exactly that we do not need to deprecate it, we can stay with both
