### ISSUE TITLE
Notify for new repo version

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/ritchie-cli#589]
**What would you like to be added**:
Add a mechanism to notify the user that a new repo release is available

**Why is this needed**:
So users can run the most up-to-date version of a formula. Useful especially for large organisations sharing a common repo

**Comment by GuillaumeFalourd** [comment]
@brunats is already working on this @henriquemoraes8 : https://github.com/ZupIT/ritchie-cli/pull/582
Your issue seems duplicated with this one: https://github.com/ZupIT/ritchie-cli/issues/431
