### ISSUE TITLE
Create installer for MacOS

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#592]
**What would you like to be added**:

Create an installer for MacOS and add this to Pipeline!

**Why is this needed**:

When we generating a new release we need to create the **.pkg** manually.

**Checklist**:

- [ ] TODO: Define Premisses

**Comment by henriquemoraeszup** [comment]
Needs alignment with SRE and sec to validate pkg certificates

**Comment by henriquemoraeszup** [comment]
Needs syncing with docs as well

**Comment by henriquemoraeszup** [comment]
@kaduartur please post here the script to generate the .pkg

**Comment by kaduartur** [comment]
> @kaduartur please post here the script to generate the .pkg

https://github.com/KosalaHerath/macos-installer-builder

**Comment by henriquemoraeszup** [comment]
If anyone is picking this issue, you can ping me, I have deployed a pkg locally and got the edited scripts
