### ISSUE TITLE
Update all formulas repositories at once

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#594]
**What would you like to be added**:

The possibility to update all formulas repositories together.

**Why is this needed**:

Today, the `rit update repo` command only update one formula repository at a time. It would be interesting to have the possibility to update all repositories with one command:

```
➜  ~ rit update repo
? Select a repository to update:   [Use arrows to move, type to filter]
> ALL
  commons
  demo
  formulas-insights
```

And then select which version I want to use for each repo during the execution.

**Comment by Harirai** [comment]
Hii @GuillaumeFalourd, I'd like to work on this issue. 
Can you guide me and help me get started?
I'm new to the Go language, going through its documentation and trying to understand file: `pkg/cmd/update_repo.go`.
Am I going in the right direction?

**Comment by GuillaumeFalourd** [comment]
Hi @Harirai

Yes, you're going in the right direction 👍 

My suggestion would be for you to test the rit update repo command first, to understand how it works.
Then, think of a solution to execute it only once for all repositories contained in the list.
Moreover, it may not be necessary to ask the user to update a repo that is already with the last available version.

Start with this, and let us know if you have any question.
