### ISSUE TITLE
Add a multiselect input type for formulas

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#600]
**What would you like to be added**:

I would like to see a new input type to allow selecting more than one option for a same input.

**Why is this needed**:

Today, there is only 3 types: `text`, `bool`, `password`, and be can use the `list` field to give options for the user to choose. However, you can only choose one item on the list at the moment, it would be great to be able to select more than one option for some inputs when necessary.

**Implementation Details**

This feature is already available in the lib survey that is used in the cli. Then just implement a new type of content for the config.json inputs called multiselect.

The behavior will be similar to the list type, but using this multiselect feature.

Example:
https://github.com/AlecAivazis/survey#multiselect

![image](https://github.com/AlecAivazis/survey/raw/master/img/multi-select-all-none.gif)

**Comment by rafaeelaudibert** [comment]
Hey @GuillaumeFalourd! I'd like to work on this, may you assign it to me?

**Comment by GuillaumeFalourd** [comment]
Hi @rafaeelaudibert , it's all yours 👍  
Thank you for contributing 🚀
