### ISSUE TITLE
Add stdin capacity to rit build formula

### ISSUE THREAD

**Issue by viniciussousazup** [ZupIT/ritchie-cli#615]
**What would you like to be added**:
Add flag `--stdin` to `rit build formula` 

**Why is this needed**:
Today the `rit build formula` need user interaction, this is a problem to CI integration and general automation.

**Comment by rodrigo-brito** [comment]
Hi @viniciussousazup, I will try to solve this.

**Comment by viniciussousazup** [comment]
Hi @rodrigo-brito, I am not working on it, If you want you can take it.

**Comment by rodrigo-brito** [comment]
No problem, I will try another one.

**Comment by GuillaumeFalourd** [comment]
> No problem, I will try another one.

@rodrigo-brito , I've assigned the issue to you as @viniciussousazup said he wasn't working on it.

But let me know if you want to work on another one, and I'll remove the assignment 👍🏼

**Comment by rodrigo-brito** [comment]
Ok, I will try this weekend.

**Comment by aronrichter** [comment]
Hey guys... how's going? Can I take this issue?

**Comment by GuillaumeFalourd** [comment]
Hi @aronrichter , thank you for your message.
We didn't get any return from @rodrigo-brito until know so if you're interested in working on this ISSUE, I can assign it to you as well 👍🏼

**Comment by rodrigo-brito** [comment]
Hi @aronrichter and @GuillaumeFalourd. Sorry for the delay in the report. 
I am focused on another issue this week, you can take it. Have fun!

**Comment by brunasilvazup** [comment]
Unfortunately, we have a new PR (https://github.com/ZupIT/ritchie-cli/pull/692) that will disable the `rit build formula` command, which is the main change in this Issue.
Thus, we will close this issue.
