### ISSUE TITLE
Enrich --help flag with more formula-related info

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#623]
**What you would like to add:**
Add a command that could be added by the --help flag that would show some detailed information about the formula without executing it. It would show the language that was made, what inputs are needed, what credentials other information available in metadata.json and even the repo link pointed to the formula readme in more detail.

Ex:
![image](https://user-images.githubusercontent.com/58859234/96806631-04944400-13eb-11eb-8859-5cb1c2e7467f.png)

**Why this is necessary:**
Users will thus know the formula better before executing it and to provide more security and help the user to identify execution problems in environments that are not prepared.

- [X] Check this box if this issue needs a documentation update

**Comment by GuillaumeFalourd** [comment]
I was wondering if it wouldn't be interesting to have these details without having to use a flag.
Maybe taking advantage of the `tutorial` being enabled.
Each time someone would execute a formula with the tutorial enabled, those informations could be displayed on the terminal before building the formula, or perform its execution.
Does it make sense @fabianofernandeszup ?

**Comment by GuillaumeFalourd** [comment]
Would be great to add this to the `--help` flag @kaduartur has been working on with this PR: https://github.com/ZupIT/ritchie-cli/pull/617 ?

**Comment by kaduartur** [comment]
> Would be great to add this to the `--help` flag @kaduartur has been working on with this PR: #617 ?

I think it makes sense to add a new session to --help flag in formulas, but I prefer to do it in another PR.

**Comment by fabianofernandeszup** [comment]
I adjusted after the suggestions.

**Comment by henriquemoraeszup** [comment]
Just updating here, we should focus on enriching the `--help` flag instead of creading a new one

**Comment by henriquemoraeszup** [comment]
IMPORTANT: We should strive to not make reads on config files for every formula, only for the specific formula if the --help flag is invoked

**Comment by henriquemoraeszup** [comment]
Consider enriching the `tree.json` file
