### ISSUE TITLE
Remove --stdin flag from core commands

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#624]
**What would you like to be added**:
I would like to remove the necessity to use the --stdin flag in the core commands.

Core commands:
 - [ ] add
 - [ ] completion
 - [ ] create
 - [ ] delete
 - [ ] init
 - [ ] list
 - [ ] set
 - [ ] show
 - [ ] update
 - [ ] build
 - [ ] upgrade
 - [ ] tutorial
 - [ ] metric

**Why is this needed**:
to facilitate the use of Ritchie with stdin

- [x] Check this box if this issue needs a documentation update

**Comment by GuillaumeFalourd** [comment]
Suggestion: Wouldn't it be interesting to keep the `--stdin` flag just for the user to get the inputs names from the command line ?

Example: `rit demo hello-world --stdin` would return something like:

```
input_text (text)
input_list (text)
input_bool (bool)
input_password (password)
```
