### ISSUE TITLE
[BUG] Files created by the formula belonging to the root user

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-cli#626]
**What happened**:
When I run a formula with a docker, the files created by the formula are created with the user **root** and group **root**

![image](https://user-images.githubusercontent.com/58859234/96818893-c867e000-13f8-11eb-8ab2-1b2dd1007420.png)

**What you expected to happen**:
The files should belong to the user who run the formula and not to the root.

**How to reproduce it (as little and precisely as possible)**:
Create a formula in a shell with the code below and run the formula with the docker flag.
You will see that in the folder that the formula was executed, the NameFile.txt file will be created, belonging to the root user and root group.

```
runFormula () {
  touch NameFile.txt
}
```

**Anything else we need to know?**:

The build of the formula also had this problem because it created the bin folder with root user. But this was resolved by applying the **chown** command to the bin folder recursively.

So I think that the same approach can be used in this case, as there is a force that copies file by file to the formula's execution folder. Just apply the chown at that time.

One approach would be to implement this CHOWN in the postrun, because in this method all files generated by the formula are copied to the folder that the form was executed in. Then, in the end, chown could be applied.

``pkg/formula/runner/post_run.go``

**Environment**:
- Ritchie version (use `rit --version`): 2.2.0
- Operating system: Ubuntu

**Comment by adi-mohan** [comment]
Hi! May I work on this issue?

**Comment by dominicksavio** [comment]
hi can i work on this issue?

**Comment by GuillaumeFalourd** [comment]
> Hi! May I work on this issue?
Hi @adi-mohan 
Sure! I'll assign it to you 👍🏼 




> hi can i work on this issue?

@dominicksavio , I've assigned the ISSUE to @adi-mohan as he asked first.
However, we have many other interesting ISSUE on this repo or on the [ritchie-formulas repo](https://github.com/ZupIT/ritchie-formulas/issues). Please, have a look!

**Comment by fabianofernandeszup** [comment]
@adi-mohan Continua atuando nessa questão?

**Comment by resmall** [comment]
Can I work on this one?

**Comment by GuillaumeFalourd** [comment]
@adi-mohan didn't answer Fabiano's message, therefore I don't think there is any problem for you to work on this one @resmall 
I'll assign it to you as well 👍🏼

**Comment by henriquemoraeszup** [comment]
We need to check this back with fabiano before refining it
