### ISSUE TITLE
Schedule formulas execution through CRON jobs

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#641]
## What I would like to see

I would like to be able to schedule the execution of specific formulas with Ritchie using a command to set [cron jobs](https://en.wikipedia.org/wiki/Cron).

## Why is it needed ?

Formulas can be created to perform any kind of tasks, and jobs may be part of them. That would give a lot more ideas and flexibility to users, as well as the opportunity to convert current jobs into formulas.

## Tasks

- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by henriquemoraeszup** [comment]
This feature will come along with a Ritchie local server to handle any asynchronous task for Ritchie

**Comment by fabianofernandeszup** [comment]
Issue moved to formulas repository:
https://github.com/ZupIT/ritchie-formulas/issues/371
https://github.com/ZupIT/ritchie-formulas/issues/372
