### ISSUE TITLE
Use credentials when consuming URL configured for the dynamic type list

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#645]
## What I would like to see

I would like to be able to use my credentials when consuming URL configured for the dynamic type list. 

This way, the tool datas could be available as inputs parameters.

For example, use the Github credentials to consume an API that will return my Github repositories to display them as options on an input text list.

Same thing could be done Gitlab, Bitbucket, CircleCI, and even with AWS to get my bucket list, or similar tools.

## Why is it needed

Currently, there is no way to manipulate the credentials set by the user to query the dynamic list in the config.json file.

This would widen the range of options for inputs configurations, as well as avoiding extra codes on the formulas implementations

**Comment by henriquemoraeszup** [comment]
Closing since we will be using formulas outputs for dynamic lists
