### ISSUE TITLE
nil pointer error with invalid tree.json

### ISSUE THREAD

**Issue by victorschumacherzup** [ZupIT/ritchie-cli#649]
I manually edited a ```tree.json``` , making it invalid. Now every time i open the terminal, this nil pointer shows up

![image](https://user-images.githubusercontent.com/51962831/97983705-79388c80-1db4-11eb-83bb-0bea74472064.png)

**Comment by GuillaumeFalourd** [comment]
What would you expect when this happen @victorschumacherzup ? An error message ? Something related to the tree.json file ?

**Comment by victorschumacherzup** [comment]
I think it can be silent, because receive a error when i open the terminal is strange

**Comment by GuillaumeFalourd** [comment]
Ok. And does this error impact Ritchie CLI behavior ?

**Comment by victorschumacherzup** [comment]
Yes, with a invalid tree, every command result in a nil pointer. In this case a informative error would be fine.

**Comment by GuillaumeFalourd** [comment]
Hmm, in that case I believe we should suggest in this message a step by step to resolve the problem, don't you think ?
Cleaning the tree.json files, updating Ritchie, something like this.

**Comment by henriquemoraeszup** [comment]
Will be resolved by #768
