### ISSUE TITLE
Portuguese landing page with english text

### ISSUE THREAD

**Issue by vitor-ramos** [ZupIT/ritchie-cli#664]
There's some english text in landing page with portuguese selected.
![Screenshot from 2020-11-11 11-36-58](https://user-images.githubusercontent.com/12222533/98824795-796b0480-2412-11eb-9e8a-7a96b2a3f931.png)
![Screenshot from 2020-11-11 11-40-37](https://user-images.githubusercontent.com/12222533/98825022-c4851780-2412-11eb-990d-bf1de5c49297.png)
![Screenshot from 2020-11-11 11-40-43](https://user-images.githubusercontent.com/12222533/98825030-c6e77180-2412-11eb-9bda-1c9fc71e58d9.png)

**Comment by GuillaumeFalourd** [comment]
Hi @vitor-ramos , thank you for your message 👍🏼 

I didn't see any error using Google Chrome here (however, my default language is english).

![Screen Shot 2020-11-11 at 11 41 12](https://user-images.githubusercontent.com/22433243/98825105-debef580-2412-11eb-92eb-0293215e4434.png)

Could you give more details about your navigator configurations please ?

**Comment by vitor-ramos** [comment]
I changed the language to Portuguese, but there’s still some text in English

**Comment by henriquemoraeszup** [comment]
@GuillaumeFalourd please transfer this issue to the correct repo, @vitor-ramos thanks for noticing that!! Closing this issue since it is not scoped to this project
