### ISSUE TITLE
Kill build concept!

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/ritchie-cli#670]
# Description 

since the income of #578, we have had less need to use an explicit build or to use the `watch` flag. Therefore, we have determined we can safely:

* remove the prompt during the autorebuild
* remove the build command
* always rebuild if changes in file are detected
* We need to execute the build during `add workspace` command to have the folder structure ready for the auto-rebuild

**Comment by henriquemoraeszup** [comment]
@gabriel-pinheiro Thanks to your initiative we are using your solution to better the UX for the user. Are you available to chat with the team so we can hear your insights and opinions?

**Comment by gabriel-pinheiro** [comment]
Hey @henriquemoraeszup

That would be awesome! I'm in =P
I'll send you my calendar on Google Chat.
