### ISSUE TITLE
Add the "latest" version to the RIT ADD REPO command automatically through STDIN

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#674]
## What would you like to be added:

When we use the STDIN (same thing with INPUT FLAG) command to add a new repository through the documentation (README or others) we use the following command:

```
echo '{"provider":"Github", "name":"demo", "version":"2.0.0", "url":"https://github.com/ZupIT/ritchie-formulas-demo", "token": null, "priority":1}' | rit add repo --stdin
```

I would like to update the way the STDIN works for this command.

## Why is it needed:

Each time a new repository version is released, it's necessary to update all documentation files using this command to the new repository version (`2.0.0` to `2.1.0` for example).

I would like to have a "latest" option for the `rit add repo` command that would always add automatically the last available version.

## Solution suggested

If the user doesn't inform the version on the STDIN command, the command should automatically add the latest version available.

```
echo '{"provider":"Github", "name":"demo", "url":"https://github.com/ZupIT/ritchie-formulas-demo", "priority":1}' | rit add repo --stdin
```

- [X] Check this box if this issue needs a documentation update

**Comment by kaduartur** [comment]
@GuillaumeFalourd to update a repo, you can run the `rit update repo` instead of adding the same repo with a different version.

**Comment by GuillaumeFalourd** [comment]
Hi @kaduartur, the ISSUE here is to allow the use to ADD a repo with its latest available version automatically, without having to inform the version (as it will be the latest).

For example, if you take a look at the README file from this repository, you'll the STDIN command to add the ritchie-formulas-demo repository. However, this command would have to be updated after each new release from the ritchie-formulas-demo repository.

If you could always add it informing the latest version available, you wouldn't need to update the README file each time.

**Comment by henriquemoraeszup** [comment]
We need to support the key word `latest` and, if not included, use it as the default term

**Comment by GuillaumeFalourd** [comment]
I was thinking here, do you think the `priority` field should be mandatory in this command?

If the priority isn't informed, the repo could be added with the lowest priority 

Example: if there are 3 repositories with priority 0, 1 and 2. The next repo could be automatically set as 3 if not informed in the command.

Don't know if this would be better to create another ISSUE or add it to this one.

**Comment by henriquemoraes8** [comment]
Removing parameters is always a good point, just not sure if lowest or highest would be better

**Comment by GuillaumeFalourd** [comment]
I believe the `lowest` priority should be the `default` value (as the user doesn't matter).

If the user wants the repository to have an highest priority (for example, 0 or 1) in that case he should inform it.
