### ISSUE TITLE
Add the "highest" priority to the RIT ADD REPO command automatically through Flag

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#680]
## What would you like to be added:

When we use the STDIN command to add a new repository through the documentation (README or others) we use the following command:

```
echo '{"provider":"Github", "name":"demo", "version":"2.0.0", "url":"https://github.com/ZupIT/ritchie-formulas-demo", "token": null, "priority":1}' | rit add repo --stdin
```

I would like to update the way the STDIN works for this command.

## Why is it needed:

If the user doesn't inform the priority on the STDIN command, the command should automatically add the highest priority available.

**By highest I mean the latest**. 
For example if priorities `0`, `1` and `2` are used for other repositories, the new repository should use the priority `0` in that case.

```
rit add repo --provider=github --name=demo --version=2.0.0 --url=https://github.com/ZupIT/ritchie-formulas-demo
```

It would make the command shorter and easier to use (the same way it has been suggested for the version field on this ISSUE: https://github.com/ZupIT/ritchie-cli/issues/674)

- [x] Check this box if this issue needs a documentation update

**Comment by henriquemoraeszup** [comment]
Here, "highest" refers to the number value. So highest number and lowest priority

**Comment by brunasilvazup** [comment]
@henriquemoraes8 e @GuillaumeFalourd
Actually in latest version of Ritchie (2.10.3) this comportment it's default, so we dont need an implementation.

> ![Screenshot from 2021-04-06 16-02-12](https://user-images.githubusercontent.com/67295691/113764631-9bcb2a80-96f1-11eb-95e4-68b1e4d4d091.png)

Do you accept it or prefer to change the default order?

**Comment by brunasilvazup** [comment]
According to our conversation, the decision is to move to the highest priority.
@GuillaumeFalourd @henriquemoraeszup
