### ISSUE TITLE
Check repository structure on RIT ADD REPO command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#698]
## What would you like to be added

- I would like the rit add repo to check if the imported repository is a ritchie repository that contains formulas.

## Why is this needed

- Today, it's possible to use the `rit add repo` command to add any Github or Gitlab repository. If the repository isn't a formulas repository, why allow to add it to the `.rit/repos` directory ?

### Example 

`rit add repo` with https://github.com/GuillaumeFalourd/developers-cheat-sheets repository 
(This repo had a release tag at that time) 

![example](https://user-images.githubusercontent.com/22433243/100481048-cd900d00-30d1-11eb-93e2-499bd92c5bab.png)

**Comment by henriquemoraeszup** [comment]
We can consider a tree.json with 0 commands an illegal repo here

**Comment by henriquemoraeszup** [comment]
We need to delete the folder as well in case it is not considered a formula repo

**Comment by matheussn** [comment]
Hi! Could I work on this issue?

**Comment by GuillaumeFalourd** [comment]
Hi @matheussn, no problem! I'll assign it to you 👍🏼 
Do you have any question about the implementation?

**Comment by matheussn** [comment]
Hi! @GuillaumeFalourd No problem! :smile:
