### ISSUE TITLE
The formula is not automatically build at its creation

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#763]
## What happened

When creating a new formula, it is necessary to execute the command at least one time to build it automatically.
However, when creating the formula, the following message appears:

`Creating and Building formula...`

![unnamed](https://user-images.githubusercontent.com/22433243/101630772-1add7a00-3a02-11eb-92bd-68fdd8c47637.gif)

## Possible Solutions

1 (easier) : correct the message leaving only `Creating formula...`
2 : Build the formula during the creation process, as it was before removing the build command.

**Comment by henriquemoraeszup** [comment]
We have deliberated with the team, the approach we will take on this issue is:

* Fix the creating formula text to not display `building`
* Remove "loading" latency from the formula creation. Make it as fast as possible

**Comment by GuillaumeFalourd** [comment]
I observed a strange behavior yesterday (more than once):

1 - I created the formula (not built)
2 - I updated the hello world template with the new implementation
3 - I executed the command (for the first time)
--> This command executed the formula with the hello world template
5 - I updated the implementation again.
6 - I executed the command (for the second time)
--> This command executed the formula with the new implementation

Shouldn't it be ok after step 3 ? (I'm using `MacOS` with the `2.5.0` CLI version)
