### ISSUE TITLE
[FEATURE] Run formulas inside a docker container

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#80]
**What would you like to be added**:
Allow running formulas inside a docker container, following the example:
![formula-docker](https://user-images.githubusercontent.com/17505818/81605771-5cdd0980-93a8-11ea-93ed-38a6deefd179.jpeg)

**Why is this needed**:
Not to depend on the host machine to execute the formulas, because the host machine may not have the necessary dependencies to run a formula.

**Comment by fghso** [comment]
Hi, @victor-schumacher! That's great news! 🎉 🎉  Thank you very much!
