### ISSUE TITLE
Create a RIT ADD WORKSPACE command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#802]
**What would you like to be added**:

A core command to add a new workspace.

**Why is this needed**:

Today, you can only add a new workspace when creating a formula.
 
However, there is a scenario when an user may need to update a formula without having the workspace configured locally, which is when cloning a new repository to update a formula inside it.

As it is today, if an user clones a repository to edit a formula inside it, he won't be able to test it locally without adding a new formula to the cloned repository, to turn it a workspace (which is strange).

- [X] Check this box if this issue needs a documentation update

**Comment by henriquemoraeszup** [comment]
Flags added `name` -> workspace name, `path` -> workspace path
