### ISSUE TITLE
Add command rit rename formula

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/ritchie-cli#817]
**What would you like to be added**:
Develop the command `rit rename formula` to change the name of a formula

**Why is this needed**:
Currently, if a developer needs to rename a formula, he renames the folder names. However, due to auto-rebuild, the new name is not detected and renaming a formula becomes cumbersome

**Flow**:
* Select a workspace
* Select the formula
* Provide the new name
* Rename the folder path
* Regenerate the tree
* Issue a warning about editing `helper.json` files

**IMPORTANT**
Do not forget to implement flags, no need for stdin as it is deprecated

- [x] Check this box if this issue needs a documentation update

**Comment by henriquemoraeszup** [comment]
We were discussing a way to not need this command and let it happen inherently by allowing the user to simply rename the folders. However, it seems that the `tree.json` would need to be updated any way. We need a command that would rename the folders and adjust the tree.

**Comment by henriquemoraeszup** [comment]
Should only work for local formulas

**Comment by brunasilvazup** [comment]
I'm working on this issue.
