### ISSUE TITLE
Add a force-update option to execute the last formula version when enabled

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#849]
**What would you like to be added**:

An option to force the user to update a specific repo (rit update repo) when a key formula has been updated for important reasons.

**Why is this needed**:

Some formulas have to be updated through time due to updated version of used tools, security reasons, or bug fixes. It could be interesting to force the user to execute the latest release of the formula to guaranty the correct version is being used. 

- [X] Check this box if this issue needs a documentation update

**Comment by fabianofernandeszup** [comment]
Call me for refinement.

**Comment by henriquemoraeszup** [comment]
This feature will be read from `config.json`
