### ISSUE TITLE
Add command 'rit update workspaces'

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#865]
**What would you like to be added**:

- To update the workspace's `tree.json` for the CLI to access new formulas.

**Why is this needed**:

- When a workspace is updated (for example with a PULL from a GIT repo) the `tree.json` file isn't updated. Consequently, the CLI can't access new formulas from the workspace, and it is necessary to delete and add the workspace again to get access to those new formula for test / implementation.

- [X] Check this box if this issue needs a documentation update

**Comment by henriquemoraeszup** [comment]
@GuillaumeFalourd How can we let the user know she needs to execute this action? Is there a way we can improve this experience? Maybe an underlying check much like the autobuild. Here we provide the tool to fix the problem but we don't let the user know that she should be expecting such problem nor which tool to use, right?

**Comment by GuillaumeFalourd** [comment]
Going for an underlying check could be a good alternative to this command, as it could directly update the `tree.json` file (instead of returning a warning to use the `rit update workspace`). I just don't know when would be the best moment to check this.

**Comment by henriquemoraeszup** [comment]
To make it clear, developing this command does not represent a long term solution, the long-term is to unify workspaces with repos and make it seamless to the user.
