### ISSUE TITLE
'rit create formula' doesn't create local workspace

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#870]
**What happened**:

- Unexpected errors creating a local workspace for new formula (as examples below):

![unnamed](https://user-images.githubusercontent.com/22433243/108771733-d3fc1c80-753a-11eb-83f6-7d22c68aed4f.png)
![unnamed (2)](https://user-images.githubusercontent.com/22433243/108771729-d2caef80-753a-11eb-83bf-e3c66c2aea81.png)
![unnamed (1)](https://user-images.githubusercontent.com/22433243/108771725-d199c280-753a-11eb-8fae-7f6cc386b55d.png)
![unnamed (3)](https://user-images.githubusercontent.com/22433243/108771740-d494b300-753a-11eb-84c0-e9a377898e3e.png)

**What you expected to happen**:

- The local workspace to be created.

**How to reproduce it (as minimally and precisely as possible)**:

- execute the `rit create formula` command selecting the option to add a new workspace manually.

**Anything else we need to know?**:

**Environment**:
- Ritchie version (use `rit --version`): 2.9.0 and 2.9.1
- Operating System: Linux + MacOS
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by henriquemoraeszup** [comment]
As shown, you need to point to an existing folder
