### ISSUE TITLE
config.json crash when have multiples conditional variables

### ISSUE THREAD

**Issue by yanBrandao** [ZupIT/ritchie-cli#873]
Hi folks, I did a little complex menu for my automation, with many conditional parameters and when I choose an alternative option, I got this error:

**What happened**:

```
Error: config.json: conditional variable rit_pizza_option not found
```

**What you expected to happen**:

Should continue alternative menu without crash

**How to reproduce it (as minimally and precisely as possible)**:
I'm sharing with u my `config.json` and a mind map with menu flow, and options to get the crash.

![image](https://user-images.githubusercontent.com/5366951/108907849-68c94d80-7601-11eb-835c-272d3ea6e6d4.png)

For details explanation, when _Bring me a Pizza_  is selected, it works like a charm, because the second menu option related to favorite pizza and address have "rit_pizza_option" variable filled.
But when _Give me a Drink_ is selected, even with all variables with _default_ value it doens't work.

Here my `config.json`:

```json
{
  "dockerImageBuilder": "ritclizup/rit-kotlin-jdk8-builder",
  "inputs": [
    {
      "label": "Wellcome to Pizza Planet :D ",
      "name": "rit_menu_option",
      "default": "Bring me a Pizza",
      "required": false,
      "items": [
        "Bring me a Pizza",
        "Give me a Drink"
      ],
      "type": "text"
    },
    {
      "cache": {
        "active": true,
        "qty": 15,
        "newLabel": "Enter a new name:"
      },
      "condition": {
        "variable": "rit_menu_option",
        "operator": "==",
        "value": "Bring me a Pizza"
      },
      "label": "Enter your name: ",
      "name": "rit_pizza_client",
      "default": "Yan",
      "required": false,
      "type": "text"
    },
    {
      "condition": {
        "variable": "rit_menu_option",
        "operator": "==",
        "value": "Bring me a Pizza"
      },
      "label": "Choose one of the options: ",
      "name": "rit_pizza_option",
      "default": "Enter an address",
      "items": [
        "Enter an address",
        "Define favorite pizza"
      ],
      "required": false,
      "type": "text"
    },
    {
      "condition": {
        "variable": "rit_pizza_option",
        "operator": "==",
        "value": "Define favorite pizza"
      },
      "label": "Tell us the pizza that you love: ",
      "name": "rit_pizza_favorite",
      "default": "Calabresa",
      "required": false,
      "type": "text"
    },
    {
      "condition": {
        "variable": "rit_menu_option",
        "operator": "==",
        "value": "Give me a Drink"
      },
      "label": "Pick your drink ",
      "name": "rit_drink_option",
      "items": [
        "Coke",
        "Orange Juice"
      ],
      "default": "Coke",
      "required": false,
      "type": "text"
    }
  ]
}

```

**What I've done to solve this problem**:

Tried to set a **default** value for every variable in config.json

**Environment**:
- Ritchie version (use `rit --version`): 2.9.1
- Operating System: Ubuntu

**Comment by GuillaumeFalourd** [comment]
Hi @yanBrandao, thank you for opening this ISSUE! 🚀 

What happened when you set the **default** values for the variables in the `config.json` file?
Did the CLI returned the same error message?

**Comment by yanBrandao** [comment]
@GuillaumeFalourd yes, I don't know if I used default parameter has need to be, but if you see all variables in this `config.json` have default value and returned the same error.

**Comment by henriquemoraeszup** [comment]
Hi Brandao! Thanks for the feedback, we will be looking into it

**Comment by yanBrandao** [comment]
@henriquemoraeszup and @GuillaumeFalourd  thanks for resolution I'm excited for the next release! \o/
