### ISSUE TITLE
We need version specific URLs/filenames for Windows installers so as to allow consistent downloads and references in other tools

### ISSUE THREAD

**Issue by dcominottim** [ZupIT/ritchie-cli#943]
**What would you like to be added**:

Currently, users are directed to download the Windows installer from https://commons-repo.ritchiecli.io/latest/ritchiecli.msi. We need to reflect the installer version in the URL/filename.

**Why is this needed**:

The limitation poses a problem in that no part of the URL or filename specifies the version to be downloaded, which will cause issues in tools that must reference a specific version of the installer (e.g.: a manifest for Windows' official package manager, winget). Furthermore, users can't get a specific version of Ritchie that is known to work for them unless they've already downloaded it (and even then, they'll have issues finding it due to the filename).

**Comment by GuillaumeFalourd** [comment]
Hi @dcominottim, after conferring here on our AWS account, it's actually possible to download a specific version of the `.msi` file through this URL:
```
https://commons-repo.ritchiecli.io/{VERSION}/installer/ritchie.msi
```
*Example*
```
https://commons-repo.ritchiecli.io/2.11.3/installer/ritchiecli.msi
```

This also works for `ritchie.deb` and `ritchie.rpm` using:

```
https://commons-repo.ritchiecli.io/{VERSION}/installer/ritchie.deb
```
and
```
https://commons-repo.ritchiecli.io/{VERSION}/installer/ritchie.rpm
```

We'll add those information to our documentation 👍🏼

**Comment by GuillaumeFalourd** [comment]
Referred PR on our documentation: https://github.com/ZupIT/docs-ritchie/pull/90

**Comment by GuillaumeFalourd** [comment]
https://github.com/ZupIT/docs-ritchie/pull/90 as been merged 👍🏼
