### ISSUE TITLE
The Java/Kotlin Formula template should come configured with the Maven Wrapper Plugin script so that the user isn't greeted with an error if 'mvn' is not configured on PATH

### ISSUE THREAD

**Issue by dcominottim** [ZupIT/ritchie-cli#947]
**What would you like to be added**:

As best practice, Maven and Gradle projects always have a wrapper script that automatically downloads/invokes Maven/Gradle, so that the user doesn't need to perform any preliminary setup of the build tool (also because the project might depend on a specific version of the tool that is different from the one configured/used otherwise by the user). We should make the standard Java/Kotlin Formula template adopt such approach.

https://maven.apache.org/plugins/maven-wrapper-plugin/

**Why is this needed**:

Right now, if an user creates a Java/Kotlin Formula and uses the local runner, he's greeted with an error message if 'mvn' is not configured on PATH. By following Maven/Gradle projects' best practices in using a wrapper script, we can be much more user friendly. In the meantime, the documentation should reflect the fact the user is expected to have Maven installed and configured on PATH if the user expects to use the local runner.

![mvn-ritchie](https://user-images.githubusercontent.com/4914233/120727869-00b4be00-c4b2-11eb-9183-a39d4e30438d.PNG)

**Comment by GuillaumeFalourd** [comment]
Hi @dcominottim , and thank you for contributing 🚀  

As this ISSUE seems specifically related to the Java and Kotlin templates, which are on the [ritchie-formulas repository](https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula), would it be possible to open this ISSUE there please?

**Comment by dcominottim** [comment]
Good, @GuillaumeFalourd! Will do! :)
